application: knobsock
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/.*
  script: main.APP
  login: required
  auth_fail_action: unauthorized

- url: /user/.*
  script: main.APP

- url: /dashboard
  static_files: static-html/dashboard.html
  upload: app
  login: required
  auth_fail_action: unauthorized

- url: (.*)/
  static_files: static-html\1/index.html
  upload: app

- url: (.*)
  static_files: static-html\1
  upload: app