application: knobsock
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/.*
  script: main.APP

- url: (.*)/
  static_files: static-html\1/dashboard.html
  upload: app

- url: (.*)
  static_files: static-html\1
  upload: app
